# Generated by Django 5.2.3 on 2025-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_test', models.DateField(auto_created=True)),
                ('test_id', models.IntegerField(unique=True)),
                ('answers_package', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
