# Generated by Django 5.2.3 on 2025-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
