# Generated by Django 5.2.3 on 2025-06-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_test_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_id',
        ),
        migrations.AlterField(
            model_name='test',
            name='date_of_test',
            field=models.DateField(auto_now_add=True),
        ),
    ]
